sudo: required
services:
    - docker

before_install:
  - docker build -t krazymir/basic-react -f Dockerfile.dev

script:
  - docker run -e CI=true krazymir/basic-react npm run test

deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  app: $AWS_APP
  env: $AWS_ENVIRONMENT
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: $AWS_BUCKET_PATH
  on:
    branch: master
  access_key_id: $AWS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"

